### ISSUE TITLE
Judyes's Custom Warp

### ISSUE THREAD

**Issue by Judyes** [saesrpg/donation-vehicle-shaders#252] opened 2021-03-28 22:08 UTC
**Vehicle ID**
604

**Wrap access**
Judyess

**Needs testing**
yes please

**Thread for reward change**
https://saesrpg.uk/topic/26026/donation-judy-amount-10-00-gbp/1

**Wrap image**
https://imgur.com/a/XpRUbRw

**Comment by tut98** [comment] 2021-03-28 22:28
Duplicate of #250 see reply there

**Closed** 2021-03-28 22:28 UTC
