### ISSUE TITLE
Update sollozzo_1 wrap

### ISSUE THREAD

**Issue by SOLLOZZO-SAES** [saesrpg/donation-vehicle-shaders#42] opened 2020-03-24 02:53 UTC
Hello Tutgreco, the left side of the car is not symmetrical to the right side. Can we try this file before a possible edition of the sollozzo_1 shader ? 
Thank you

Image : https://i.imgur.com/fPJM9Va.png

**Comment by tutgreco** [comment] 2020-03-24 15:07
Duplicate of #37

**Closed by tutgreco** 2020-03-24 15:07 UTC
