### ISSUE TITLE
MatizZ's Custom wrap request

### ISSUE THREAD

**Issue by iMatizZ** [saesrpg/donation-vehicle-shaders#474] opened 2022-07-31 19:13 UTC
**Vehicle ID** Glendale (damaged) 604

**Wrap access** matizz_6

**Thread for reward change** https://saesrpg.uk/topic/33200/donation-undefined-amount-10-00-gbp

**Translations** -

**Wrap image**
![glendale](https://user-images.githubusercontent.com/46718789/182041566-6aca9ead-d568-4fd3-b3d4-63105316069a.png)

**Comment by tut98** [comment] 2022-08-01 14:04
Duplicate of #352, you can ask the owner for permission to use their wrap

**Closed by tut98** 2022-08-01 14:04 UTC
Labels: Status: In Progress
